version: '3'
services:
 samplepong:
    image: "sample-pong:1.2.0-SNAPSHOT"
    hostname: samplepong
    links:
      - sampleeureka
      - sampleconfig
    environment:
      EUREKA_HOST: sampleeureka
      EUREKA_PORT: 8761
      SERVER_PORT: 8080
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8082:8080"

  sampleping:
    image: "sample-ping:1.2.0-SNAPSHOT"
    hostname: sampleping
    links:
      - sampleeureka
      - sampleconfig
      - samplepong
    environment:
      EUREKA_HOST: sampleeureka
      EUREKA_PORT: 8761
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8080:8080"
