steps:
- name: openjdk:11
  entrypoint: "../mvnw"
  args: ["test"]
- name: openjdk:11
  entrypoint: "../mvnw"
  args: ["package", "-Dmaven.test.skip=true"]
- name: gcr.io/cloud-builders/docker
  args: ["build", "-t", "gcr.io/$PROJECT_ID/hellospring", "--build-arg=JAR_FILE=target/hello-spring-1.0.0.jar", "."]
images: ["gcr.io/$PROJECT_ID/hellospring"]